import Link from 'next/link';
import {L} from './L';
import {InfoNote} from './InfoNote';
import {UploadInput} from './UploadInput';
import {saveVenueRequirementAction,approveVenuePlanAction} from '../app/venues/actions';
import {venueRequirementEditors,type VenueEditor} from '../lib/rules/venue-workflow';
import {acceptAttribute,acceptHint} from '../lib/rules/uploads';
import type {VenueWorkspaceData} from './VenueWorkspace';
const button:React.CSSProperties={padding:'10px 22px',border:0,borderRadius:24,background:'var(--brand)',color:'var(--bg)'};
export function VenueRequirementList({w,role='organizer',token,saved}:{w:VenueWorkspaceData;role?:VenueEditor;token?:string;saved?:string|undefined}) {
 const id=w.venue.id;
 return <>{['required','optional'].map(group=>{const rows=w.requirements.filter(r=>r.optional===(group==='optional'));return rows.length?<section key={group}><h3><L en={group==='required'?'Required':'Recommended (optional)'} ar={group==='required'?'مطلوب':'موصى به (اختياري)'}/></h3><div data-region="requirements" style={{display:'grid',gap:12,marginBlockEnd:28}}>{rows.map(r=>{
 const key=String(r.n),canEdit=w.editable&&w.level&&venueRequirementEditors(r.n,w.level).includes(role);
 const receipt=r.receipts.find(c=>r.n===20?c.invitation_token===token:true);
 const values=r.n===20&&role!=='organizer'?(receipt?JSON.parse(receipt.answers):{}):w.answers[key]??{};
 const fileKey=r.n===20&&token?`20-${token}`:key,file=w.files.find(f=>f.docKey===fileKey&&f.hasFile);
 const doneForMe=r.n===20?Boolean(receipt):r.done||r.awaitingApproval;
 const fields=<form action={saveVenueRequirementAction.bind(null,id,key)}><input type="hidden" name="assessmentVersion" value={w.assessmentVersion??''}/><input type="hidden" name="workRevision" value={w.workRevision}/><div style={{display:'grid',gap:16}}>{r.fields.map(f=><label key={f.key} style={{display:'grid',gap:6}}><L en={f.en} ar={f.ar}/><textarea required name={f.key} defaultValue={values[f.key]??''} rows={2} maxLength={5000} style={{width:'100%',padding:12,border:'1px solid var(--line)',borderRadius:8,background:'var(--bg)',fontFamily:'inherit',fontSize:15}}/></label>)}</div><label style={{display:'grid',gap:8,marginBlock:20}}><L en={r.fileRequired?'Required document':'Supporting document (optional)'} ar={r.fileRequired?'مستند مطلوب':'مستند داعم (اختياري)'}/><UploadInput name="file" accept={acceptAttribute()} required={r.fileRequired&&!file}/><small><L en={acceptHint().en} ar={acceptHint().ar}/></small></label>{role!=='organizer'?<label style={{display:'flex',gap:10,marginBlock:18}}><input type="checkbox" name="confirm" value="yes" required/><L en="I confirm these arrangements for this venue." ar="أؤكّد هذه الترتيبات لهذا الموقع."/></label>:null}<button style={button}><L en={role==='organizer'?'Save':'Mark complete'} ar={role==='organizer'?'حفظ':'تأكيد الاكتمال'}/></button></form>;
 return <details key={key} id={`r-${key}`} data-requirement={key} open={saved===key} style={{background:'var(--surface2)',borderRadius:12,borderInlineStart:`3px solid ${r.done?'var(--brand)':r.optional?'var(--line)':'var(--accent-ink)'}`,padding:20,scrollMarginBlockStart:24}}><summary style={{cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,minHeight:40}}><strong><L en={r.en} ar={r.ar}/></strong><span data-completion={r.done?'complete':'pending'} style={{flexShrink:0,color:r.done?'var(--brand)':r.optional?'var(--muted)':'var(--accent-ink)',background:r.done?'var(--brand-soft)':r.optional?'var(--bg)':'var(--accent-soft)',padding:'5px 10px',borderRadius:20,fontSize:13}}><L en={r.done?'Complete':r.awaitingApproval?'Awaiting approval':r.optional?'Optional':'Pending'} ar={r.done?'مكتمل':r.awaitingApproval?'بانتظار الاعتماد':r.optional?'اختياري':'قيد الانتظار'}/></span></summary>
 <div style={{display:'flex',gap:8,alignItems:'center',marginBlock:'12px 20px'}}><L en={r.n===1?'From venue details':r.n===3?'Confirmed Medical Director':r.clinical?(r.n===15?'Medical Director':r.n===20?'Each EMS agency':'Medical Director or EMS agency'):'Organizer'} ar={r.n===1?'من تفاصيل الموقع':r.n===3?'المدير الطبي المؤكّد':r.clinical?(r.n===15?'المدير الطبي':r.n===20?'كل جهة إسعاف':'المدير الطبي أو جهة الإسعاف'):'المنظّم'}/><InfoNote><L en={r.valueEn} ar={r.valueAr}/></InfoNote></div>
 {(!canEdit||doneForMe)?<dl style={{display:'grid',gap:12}}>{r.fields.map(f=><div key={f.key}><dt style={{color:'var(--muted)',fontSize:13}}><L en={f.en} ar={f.ar}/></dt><dd style={{margin:0,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{values[f.key]||'—'}</dd></div>)}</dl>:null}
 {file?<p><a href={`/api/venue-documents/${id}/${fileKey}`} target="_blank" rel="noreferrer"><L en="View attached file" ar="عرض الملف المرفق"/> · {file.fileName}</a></p>:null}
 {r.receipts.map(c=>{const data=JSON.parse(c.answers);return <p key={c.invitation_token} style={{fontSize:13,color:'var(--muted)'}}><L en="Completed by" ar="أكمله"/> {c.display_name} · {c.completed_at.slice(0,10)} {r.n===20&&data.fileKey?<a href={`/api/venue-documents/${id}/${data.fileKey}`} target="_blank" rel="noreferrer"><L en="View declaration" ar="عرض الإقرار"/></a>:null}</p>})}
 {r.n===2&&w.approval?<p><L en="Medical Director approval" ar="اعتمدها"/> {w.approval.display_name} · {w.approval.approved_at.slice(0,10)}</p>:null}
 {canEdit?(doneForMe?<details style={{marginBlockStart:20}}><summary style={{cursor:'pointer',color:'var(--brand)',marginBlockEnd:16}}><L en="Update these answers" ar="تعديل هذه الإجابات"/></summary>{fields}</details>:fields):null}
 {!r.done&&role==='organizer'&&r.clinical?<p><Link href={`/venues/${id}/team`}><L en="View medical team and invitations" ar="عرض الفريق الطبي والدعوات"/></Link></p>:null}
 {r.n===1&&!r.done&&role==='organizer'?<Link href={`/venues/${id}/details`}><L en="Complete contact details" ar="إكمال بيانات الاتصال"/></Link>:null}
 {r.n===3&&role==='organizer'?<Link href={`/venues/${id}/team`}><L en="Manage Medical Director invitation" ar="إدارة دعوة المدير الطبي"/></Link>:null}
 {r.awaitingApproval&&role==='director'&&w.editable?<form action={approveVenuePlanAction.bind(null,id)}><input type="hidden" name="assessmentVersion" value={w.assessmentVersion??''}/><input type="hidden" name="workRevision" value={w.workRevision}/><label style={{display:'flex',gap:10,marginBlock:18}}><input type="checkbox" name="confirm" value="yes" required/><L en="I have reviewed and approve this plan and the medical arrangements." ar="راجعت هذه الخطة والترتيبات الطبية وأعتمدها."/></label><button style={button}><L en="Approve medical plan" ar="اعتماد الخطة الطبية"/></button></form>:null}
 </details>;
 })}</div></section>:null;})}</>;
}
