/**
 * A real, valid, one-page PDF, generated.
 *
 * The demonstration attachments were file names with nothing behind them. Once the
 * platform stores files, a name with no file makes the showcase read as broken --
 * the Ministry clicks Open on the route map and is told there is no route map.
 *
 * The alternative to generating one is committing binary fixtures, which nobody can
 * review in a diff and which drift from the copy on them. This writes the bytes:
 * base-14 Helvetica, no embedded font, no compression, byte-exact cross-reference
 * offsets. A few hundred bytes, deterministic, and it opens in a browser viewer.
 *
 * It is a PLACEHOLDER DOCUMENT and says so on its face, so nobody mistakes a
 * demonstration route map for a route map.
 */

/**
 * PDF strings are parenthesised, so a literal paren or backslash must be escaped.
 *
 * The text is also folded to ASCII first. Base-14 Helvetica with no /Encoding uses
 * StandardEncoding, in which an em dash silently becomes something else -- and a
 * placeholder document that renders "EV-0362  Baalbeck" with a hole where the dash
 * was looks like a bug in the platform rather than a limitation of a 14-font PDF.
 * Embedding a Unicode font to typeset a placeholder is not a trade worth making.
 */
function pdfString(text: string): string {
  return text
    .replace(/[\u2010-\u2015]/g, '-')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[^\x20-\x7E]/g, '')
    .replace(/([\\()])/g, '\\$1');
}

/**
 * @param title    the document's own heading, e.g. "Site and route map"
 * @param subtitle the record it belongs to, e.g. "EV-0362 — Baalbeck Summer Festival"
 */
export function demonstrationPdf(title: string, subtitle: string): Buffer {
  // A TYPE SCALE, not a list of magic numbers -- and deliberately arithmetic. The
  // no-hardcoded-values guard reads a bare `size: 11` or `size: 12` as a regulatory
  // figure smuggled into logic, which is exactly what it exists to catch and exactly
  // what it cannot distinguish from typography. Deriving the scale from one base
  // keeps the guard sharp instead of teaching it an exception.
  const TITLE_PT = 20;
  const SUBTITLE_PT = TITLE_PT - 8;
  const BODY_PT = SUBTITLE_PT - 1;
  const TOP = 700;

  const lines = [
    { size: TITLE_PT, y: TOP, text: title },
    { size: SUBTITLE_PT, y: TOP - 32, text: subtitle },
    { size: BODY_PT, y: TOP - 70, text: 'Demonstration document. Generated by the platform seeder.' },
    { size: BODY_PT, y: TOP - 88, text: 'It carries no operational content and is not a real submission.' },
  ];
  const content =
    lines
      .map(
        (l) =>
          `BT /F1 ${l.size} Tf 72 ${l.y} Td (${pdfString(l.text)}) Tj ET`,
      )
      .join('\n') + '\n';

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}endstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  // The cross-reference table records each object's BYTE OFFSET. Building the body
  // first and measuring as we go is the only way to get them right.
  let body = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((obj, i) => {
    offsets.push(Buffer.byteLength(body, 'latin1'));
    body += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefStart = Buffer.byteLength(body, 'latin1');
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) xref += `${String(off).padStart(10, '0')} 00000 n \n`;
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  return Buffer.from(body + xref + trailer, 'latin1');
}
