import { VENUE_STATUS, venueStatusForDecision } from '../../../../lib/rules/venue-workflow';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { MinistryShell } from '../../../../components/MinistryShell';
import { L } from '../../../../components/L';
import { requireMinistryPage } from '../../../../lib/ministry-auth';
import { getDb } from '../../../../lib/db';
import { can } from '../../../../lib/rules';
import { venuePackageFor } from '../../../../lib/venue/workspace';
import type { VenueAnswers, VenueRequirement } from '../../../../lib/rules/venue-workflow';
import { reviewVenuePackageAction } from '../../../venues/actions';
export default async function Review({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{revision?:string;error?:string}>}){
 const account=await requireMinistryPage('viewSubmission');const {id}=await params;const q=await searchParams;const db=getDb();const owner=db.prepare('SELECT account_id,is_demo FROM venues WHERE id=?').get(id) as {account_id:number;is_demo:number}|undefined;if(!owner||owner.is_demo!==+account.isDemo)notFound();
 const w=venuePackageFor(owner.account_id,id)!;const history=db.prepare('SELECT revision,submitted_at,decision,review_note,reviewed_at,snapshot FROM venue_package_history WHERE venue_id=? ORDER BY revision DESC').all(id) as unknown as {revision:number;submitted_at:string;decision:string|null;review_note:string;reviewed_at:string|null;snapshot:string}[];
 const record=q.revision?history.find(h=>String(h.revision)===q.revision):history[0];if(!record)notFound();
 const s=JSON.parse(record.snapshot) as {venue:typeof w.venue;district:string;point:{lat:number;lng:number}|null;level:number;requirements:VenueRequirement[];answers:VenueAnswers;assessmentVersion:number;approval?:{display_name:string;approved_at:string}};
 const assessment=db.prepare('SELECT answers,derivation FROM venue_assessments WHERE venue_id=? AND version=?').get(id,s.assessmentVersion) as {answers:string;derivation:string}|undefined;
 const files=db.prepare('SELECT f.doc_key,f.file_name FROM venue_package_files f JOIN venue_package_history h ON h.id=f.package_id WHERE h.venue_id=? AND h.revision=?').all(id,record.revision) as unknown as {doc_key:string;file_name:string}[];
 return <MinistryShell account={account}><Link href="/ministry/venues"><L en="Hosting venues" ar="مواقع الاستضافة"/></Link><h1><L en={s.venue.nameEn} ar={s.venue.nameAr}/></h1><p>{id} · <L en={`Submission ${record.revision}`} ar={`الطلب ${record.revision}`}/></p>
 {q.error?<p role="alert"><L en="Add a reason when requesting changes. If another reviewer has already acted, reload the file." ar="أضيفوا سبباً عند طلب التعديل. إذا سبقتكم مراجعة أخرى، أعيدوا تحميل الملف."/></p>:null}
 <section data-region="venue-review-summary" style={{padding:24,border:'1px solid var(--line)',borderRadius:12}}><h2><L en="Venue at a glance" ar="ملخّص الموقع"/></h2><p><L en="Level" ar="المستوى"/> {s.level} · <L en="Capacity" ar="السعة"/> {s.venue.licensedCapacity}</p><p>{s.venue.category} · {s.district}</p><p><L en={s.venue.addressMunicipalityEn} ar={s.venue.addressMunicipalityAr}/></p><p>{s.venue.responsibleContact}</p>{s.point?<a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${s.point.lat}&mlon=${s.point.lng}#map=17/${s.point.lat}/${s.point.lng}`}><L en="View map pin" ar="عرض الموقع على الخريطة"/></a>:null}</section>
 <h2><L en="Submitted requirements" ar="المتطلبات المقدّمة"/></h2>{s.requirements.map(r=><section key={r.n} style={{padding:20,border:'1px solid var(--line)',borderRadius:12,marginBlock:12}}><h3><L en={r.en} ar={r.ar}/></h3><p><L en={r.optional?'Optional':'Required'} ar={r.optional?'اختياري':'مطلوب'}/> · <L en={r.valueEn} ar={r.valueAr}/></p><dl>{r.fields.map(f=><div key={f.key} style={{marginBlock:16}}><dt style={{color:'var(--muted)'}}><L en={f.en} ar={f.ar}/></dt><dd style={{margin:0,whiteSpace:'pre-wrap'}}>{s.answers[String(r.n)]?.[f.key]||'—'}</dd></div>)}</dl>{(r as typeof w.requirements[number]).receipts?.map(c=><p key={c.invitation_token}><L en="Completed by" ar="أكمله"/> {c.display_name} · {c.completed_at}</p>)}{r.n===2&&s.approval?<p><L en="Medical Director approval" ar="اعتمدها المدير الطبي"/>: {s.approval.display_name} · {s.approval.approved_at}</p>:null}{files.filter(f=>f.doc_key===String(r.n)||(r.n===20&&f.doc_key.startsWith('20-'))).map(f=><a key={f.doc_key} href={`/api/venue-documents/${id}/${f.doc_key}?revision=${record.revision}`} target="_blank" rel="noreferrer"><L en="Open document" ar="فتح المستند"/> · {f.file_name}</a>)}</section>)}
 {assessment?<details style={{marginBlock:24}}><summary><L en="Assessment answers" ar="إجابات التقييم"/></summary>{(await import('../../../../lib/rules/load')).DOMAINS.map((d,i)=><p key={i}><L en={d.en} ar={d.ar}/> · <L en={d.options.find(o=>o.score===JSON.parse(assessment.answers)[i])?.en??'—'} ar={d.options.find(o=>o.score===JSON.parse(assessment.answers)[i])?.ar??'—'}/></p>)}</details>:null}
 {record.decision?<p><L en="Review outcome" ar="نتيجة المراجعة"/>: <L en={VENUE_STATUS[venueStatusForDecision(record.decision as 'satisfied'|'revision'|'incomplete')].en} ar={VENUE_STATUS[venueStatusForDecision(record.decision as 'satisfied'|'revision'|'incomplete')].ar}/> · {record.review_note}</p>:null}
 {w.status==='submitted'&&record.revision===w.revision&&can(account.role,'recordOutcome')?<form action={reviewVenuePackageAction.bind(null,id)} style={{padding:24,background:'var(--surface2)',borderRadius:12}}><h2><L en="Record your review" ar="تسجيل المراجعة"/></h2><input name="revision" type="hidden" value={record.revision}/><label style={{display:'grid',gap:8}}><L en="Notes for the operator" ar="ملاحظات للجهة المشغّلة"/><textarea name="note" rows={4} style={{width:'100%',padding:12,border:'1px solid var(--line)',borderRadius:8}}/></label><div style={{display:'flex',gap:12,flexWrap:'wrap',marginBlockStart:20}}>{[{key:'satisfied',en:'Requirements satisfied',ar:'المتطلبات مستوفاة'},{key:'revision',en:'Request changes',ar:'طلب تعديلات'},{key:'incomplete',en:'Incomplete',ar:'غير مكتمل'}].map(d=><button key={d.key} name="decision" value={d.key} style={{padding:'12px 20px',border:'1px solid var(--line)',borderRadius:24,background:d.key==='satisfied'?'var(--brand)':'var(--bg)',color:d.key==='satisfied'?'var(--bg)':'var(--ink)'}}><L en={d.en} ar={d.ar}/></button>)}</div></form>:null}
 <h2><L en="Submission history" ar="سجل الطلبات"/></h2>{history.map(h=><p key={h.revision}><Link href={`/ministry/venues/${id}?revision=${h.revision}`}><L en={`Submission ${h.revision}`} ar={`الطلب ${h.revision}`}/> · {h.submitted_at}</Link></p>)}
 </MinistryShell>;
}
