import {VenueWorkspace} from '../../../../components/VenueWorkspace';
import {ownedVenuePage} from '../../../../lib/venue/page';
import {venueLocalEmsContactApplies} from '../../../../lib/rules/venue-workflow';
import {L} from '../../../../components/L';
import {inviteVenuePartnerAction,withdrawVenuePartnerAction,saveVenueLocalEmsContactAction} from '../../team-actions';
import {InvitationLinkBlock} from '../../../events/[id]/requirements/InvitationLinkBlock';
const input:React.CSSProperties={padding:12,border:'1px solid var(--line)',borderRadius:8,background:'var(--bg)',minWidth:0,width:'100%'};
export default async function Team({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;saved?:string}>}){
 const {id}=await params;const {account,w}=await ownedVenuePage(id);const q=await searchParams;
 return <VenueWorkspace account={account} w={w} active="team"><h2><L en="Medical team" ar="الفريق الطبي"/></h2>{q.error?<p role="alert"><L en={q.error==='duplicate'?'This invitation already exists. Withdraw it before replacing it.':q.error==='local'?'Enter the local EMS name and phone, then confirm the contact.':'Enter a name and a valid email address.'} ar={q.error==='duplicate'?'هذه الدعوة موجودة. اسحبوها قبل استبدالها.':q.error==='local'?'أدخلوا اسم جهة الإسعاف المحلية ورقمها، ثم أكّدوا الاتصال.':'أدخلوا اسماً وبريداً إلكترونياً صالحاً.'}/></p>:null}
 {q.saved?<p role="status"><L en="Contact saved. Your requirements have been updated." ar="حُفظت بيانات الاتصال وحُدّثت المتطلبات."/></p>:null}{(['ems','director'] as const).map(kind=><section key={kind} style={{padding:24,border:'1px solid var(--line)',borderRadius:12,marginBlock:24}}><h3 style={{marginBlockStart:0}}><L en={kind==='ems'?'EMS agencies':'Medical Director'} ar={kind==='ems'?'جهات الإسعاف':'المدير الطبي'}/></h3>{kind==='director'?<p><L en={w.level===3?'Required at Level 3':'Optional at this level'} ar={w.level===3?'مطلوب في المستوى الثالث':'اختياري في هذا المستوى'}/></p>:null}
 {w.invitations.filter(i=>i.kind===kind).map(i=><div key={i.token} style={{paddingBlock:16,borderBlockStart:'1px solid var(--line)'}}><strong>{i.name}</strong><p>{i.email}{i.phone?<> · <bdi>{i.phone}</bdi></>:null} · <L en={i.status==='confirmed'?'Accepted':i.status==='declined'?'Declined':i.status==='withdrawn'?'Withdrawn':'Awaiting response'} ar={i.status==='confirmed'?'مقبولة':i.status==='declined'?'مرفوضة':i.status==='withdrawn'?'مسحوبة':'بانتظار الرد'}/></p>{i.note?<p>{i.note}</p>:null}{i.status==='confirmed'?<p><L en={`${w.contributions.filter(c=>c.invitation_token===i.token).length} requirements completed`} ar={`${w.contributions.filter(c=>c.invitation_token===i.token).length} متطلبات مكتملة`}/></p>:null}
 {i.status==='nominated'?<><p style={{fontSize:13}}><L en={i.delivery==='sent'?'Invitation email sent.':i.delivery==='demo'?'Demo invitation — share this link.':'Email not sent. Share this invitation link.'} ar={i.delivery==='sent'?'أُرسلت الدعوة بالبريد.':i.delivery==='demo'?'دعوة تجريبية — شاركوا هذا الرابط.':'لم يُرسل البريد. شاركوا رابط الدعوة.'}/></p><InvitationLinkBlock token={i.token} path={`/venue-invitations/${i.token}`}/></>:null}
 {w.editable&&['confirmed','nominated'].includes(i.status)?<form action={withdrawVenuePartnerAction.bind(null,id,i.token)}><button type="submit" style={{marginBlockStart:12}}><L en="Withdraw invitation" ar="سحب الدعوة"/></button></form>:null}</div>)}
 {w.editable&&w.level&&(kind==='ems'||!w.invitations.some(i=>i.kind==='director'&&['nominated','confirmed'].includes(i.status)))?<form action={inviteVenuePartnerAction.bind(null,id)} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:16,alignItems:'end'}}><input type="hidden" name="kind" value={kind}/><label><L en={kind==='ems'?'Agency name':'Physician name'} ar={kind==='ems'?'اسم الجهة':'اسم الطبيب'}/><input style={input} name="name" required/></label><label><L en="Email" ar="البريد الإلكتروني"/><input style={input} name="email" type="email" required/></label><button style={{...input,background:'var(--brand)',color:'var(--bg)'}}><L en="Send invitation" ar="إرسال الدعوة"/></button></form>:null}
 </section>)}
 {venueLocalEmsContactApplies(w.level,w.invitations.some(i=>i.kind==='ems'&&['nominated','confirmed'].includes(i.status)))?<section style={{padding:24,border:'1px solid var(--line)',borderRadius:12,marginBlock:24}}><h3><L en="Local EMS contact" ar="جهة الاتصال بالإسعاف المحلي"/></h3><p><L en="At Level 1, you can confirm a local EMS contact without inviting an on-site agency." ar="في المستوى الأول، يمكنكم تأكيد جهة اتصال إسعافية محلية دون دعوة جهة للعمل في الموقع."/></p>{w.editable?<form action={saveVenueLocalEmsContactAction.bind(null,id)} style={{display:'grid',gap:16}}><label><L en="EMS agency" ar="جهة الإسعاف"/><input name="agency" required defaultValue={w.answers['7']?.agency??''} style={input}/></label><label><L en="Phone number" ar="رقم الهاتف"/><input name="phone" type="tel" required defaultValue={w.answers['7']?.phone??''} style={input}/></label><label style={{display:'flex',gap:10}}><input name="confirm" type="checkbox" value="yes" required/><L en="I have confirmed this EMS contact." ar="أكّدت بيانات الاتصال بجهة الإسعاف هذه."/></label><button><L en="Save contact" ar="حفظ بيانات الاتصال"/></button></form>:<p>{w.answers['7']?.agency} · <bdi>{w.answers['7']?.phone}</bdi></p>}</section>:null}
 </VenueWorkspace>;
}
