import { test, expect, type Page } from '@playwright/test';
import { signInAs } from '../helpers/signin';
import { useLanguage } from '../helpers/language';
async function firstSection(page: Page) {
  const toggle = page.getByRole('button', { name: /^1 / }).and(page.locator('[aria-expanded]'));
  if (await toggle.getAttribute('aria-expanded') !== 'true') await toggle.click();
  return page.getByRole('textbox', { name: /^1\./ });
}
test('Level 2 plan is optional, EMS fills it, organizer sees it automatically in separate team tabs', async ({ page, browser, baseURL }) => {
  await signInAs(page, 'test_organizer');
  await page.goto('/events/EV-0418/requirements');
  // The section heading carries its number ("3 Medical Director (optional)"), so match the title.
  await expect(page.getByRole('heading',{name:/Medical Director \(optional\)$/})).toBeVisible();
  const card = page.locator('[data-document=plan]');
  await expect(card.locator('summary')).toContainText('Recommended');
  await card.locator('summary').click();
  await expect(card).toContainText('Completed by the Medical Director or EMS agency.');
  await expect(card.locator('input[type=file]')).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Event sections' }).getByRole('link', { name: 'EMS agencies', exact: true }).click();
  await expect(page.locator('[data-region=medical-team-party]').first()).toBeVisible();
  await page.getByRole('link', { name: 'View plan', exact: true }).click();
  await expect(page.getByText('Recommended — not required to submit', { exact: true })).toBeVisible();
  await expect(page.locator('main textarea, main input[type=file]')).toHaveCount(0);
  const readonlyFirst = page.locator('[data-region=plan-readonly] details').first();
  if (await readonlyFirst.count()) await readonlyFirst.locator('summary').click();
  const ems = await browser.newPage({ baseURL: baseURL! });
  await signInAs(ems, 'test_ems');
  await ems.goto('/events/EV-0418/participation');
  await ems.locator('[data-region=ems-plan]').getByRole('link').click();
  await ems.getByRole('button', { name: 'Write the plan here', exact: true }).click();
  await (await firstSection(ems)).fill('Level 2 shared plan prepared by the EMS agency.');
  await ems.getByRole('button', { name: /^Save the plan/ }).click();
  await expect(ems.getByText('Saved.', { exact: true })).toBeVisible();
  await expect(page.locator('[data-region=plan-readonly]')).toContainText('Level 2 shared plan prepared by the EMS agency.', { timeout: 20_000 });
  const sharedSection = page.locator('[data-region=plan-readonly] details').first();
  if (await sharedSection.getAttribute('open') === null) await sharedSection.locator('summary').click();
  await expect(page.getByText('Level 2 shared plan prepared by the EMS agency.', { exact: true })).toBeVisible();
  await page.goto('/events/EV-0418/medical-team?tab=director');
  await expect(page.getByText('No Medical Director has been invited.', { exact: true })).toBeVisible();
  await expect(page.locator('[data-region=shared-plan-summary]')).toContainText('Last saved by');
  await page.getByRole('navigation', { name: 'Event sections' }).getByRole('link', { name: 'EMS agencies', exact: true }).click();
  await expect(page).toHaveURL(/tab=ems/);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/annex-b-team-mobile.png', fullPage: true });
  expect((await ems.request.get('/events/EV-0418/medical-team?tab=ems')).status()).toBe(404);
  await ems.close();
});
test('an untouched EMS editor receives the Director’s saved plan without re-entry', async ({ page, browser, baseURL }) => {
  await signInAs(page, 'test_director');
  await page.goto('/events/EV-0362/plan');
  const originalFile = await page.request.get('/api/documents/EV-0362/plan-document');
  expect(originalFile.status()).toBe(200);
  const originalBytes = await originalFile.body();
  await page.getByRole('button', { name: 'Write the plan here', exact: true }).click();
  await (await firstSection(page)).fill('Initial Director version.');
  await page.getByRole('button', { name: /^Save the plan/ }).click();
  await expect(page.getByText('Saved.', { exact: true })).toBeVisible();
  const ems = await browser.newPage({ baseURL: baseURL! });
  await signInAs(ems, 'test_ems');
  await ems.goto('/events/EV-0362/plan');
  await expect(await firstSection(ems)).toHaveValue('Initial Director version.');
  await (await firstSection(page)).fill('Updated shared plan from the Director.');
  await page.getByRole('button', { name: /^Save the plan/ }).click();
  await expect(page.getByText('Saved.', { exact: true })).toBeVisible();
  await expect(await firstSection(ems)).toHaveValue('Updated shared plan from the Director.', { timeout: 20_000 });
  await ems.close();
  // Preserve the complete demonstration plan for other independent journeys.
  await page.getByRole('button',{name:'Attach an existing plan',exact:true}).click();
  await page.locator('[data-region=plan-attach] input[type=file]').setInputFiles({name:'restored-medical-plan.pdf',mimeType:'application/pdf',buffer:originalBytes});
  await expect(page.getByText('Attached: restored-medical-plan.pdf',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:/^Save the plan/}).click();
  await expect(page.getByText('Saved.',{exact:true})).toBeVisible();
});
test('organizer Medical Director and EMS views work in Arabic and show signed agency details', async ({ page, context }) => {
  await signInAs(page, 'test_organizer');
  await useLanguage(context, 'ar');
  await page.goto('/events/EV-0362/medical-team?tab=director');
  await expect(page.locator('html')).toHaveAttribute('dir','rtl');
  await expect(page.locator('[data-region=team-governance]')).toBeVisible();
  await expect(page.locator('main textarea, main input')).toHaveCount(0);
  await page.goto('/events/EV-0362/medical-team?tab=ems');
  const declaration = page.locator('[data-region=team-declaration]').first();
  await declaration.locator('summary').click();
  await expect(declaration).toContainText('مقدّم');
  await page.evaluate(() => window.scrollTo(0,0));
  await page.screenshot({ path: 'test-results/annex-b-team-arabic.png', fullPage: true });
});
