import {test,expect,type Page} from '@playwright/test';
import {DatabaseSync} from 'node:sqlite';
import {signInAs} from '../helpers/signin';
import {mockMapTiles,chooseMapPoint} from '../helpers/facility-map';
async function rowOpen(page:Page,key:string){const r=page.locator(`[data-requirement="${key}"]`);if(await r.getAttribute('open')===null)await r.locator('summary').first().click();return r;}
async function fillRow(page:Page,key:string,medical=false){const r=await rowOpen(page,key);for(const t of await r.locator('textarea').all())await t.fill(`Confirmed ${key} coverage, staffing and contact +9613111111.`);const file=r.locator('input[type=file]');if(await file.count()&&await file.getAttribute('required')!==null)await file.setInputFiles({name:'venue-medical.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nMedical document')});if(medical)await r.locator('input[name=confirm]').check();await r.getByRole('button',{name:medical?'Mark complete':'Save',exact:true}).click();await expect(page).toHaveURL(new RegExp(`saved=${key}`));}
test('venue medical team completes the package; organizer and Ministry see the answers and approval',async({page,browser,baseURL},info)=>{
 await mockMapTiles(page);await signInAs(page,'test_organizer');await page.goto('/venues/new');
 for(const[k,v]of Object.entries({name:'Venue team browser test',nameAr:'موقع اختبار الفريق الطبي',address:'Beirut main road',contactName:'Venue operator',contactPhone:'+9613111111',capacity:'5000'}))await page.locator(`input[name=${k}]`).fill(v);
 await page.locator('select[name=category]').selectOption('hall');await page.locator('select[name=district]').selectOption('Beirut');await page.getByRole('button',{name:'Yes',exact:true}).first().click();await page.getByRole('button',{name:'No',exact:true}).nth(1).click();await chooseMapPoint(page);await page.getByRole('button',{name:'Continue to assessment',exact:true}).click();await expect(page).toHaveURL(/\/VN-\d+\/assessment/);const id=page.url().match(/VN-\d+/)![0];
 await page.getByLabel(/Most people at the same time during a routine operating session/).fill('5000');for(const d of await page.locator('[data-domain]').all())await d.locator('button').last().click();await page.getByLabel(/Authorized representative/).fill('Operator');await page.getByLabel(/Position/).fill('Manager');await page.getByRole('button',{name:'Save and view requirements',exact:true}).click();await expect(page).toHaveURL(new RegExp(`${id}/requirements`));
 await expect(page.locator('[data-requirement="1"] [data-completion]')).toHaveAttribute('data-completion','complete');await expect(page.locator('[data-requirement="5"] textarea')).toHaveCount(0);expect((await page.request.get(`/venues/${id}/certificate`)).status()).toBe(404);
 await page.goto(`/venues/${id}/details`);await expect(page.locator('[data-region=venue-details-read-only]')).toContainText('Venue operator');await expect(page.getByRole('button',{name:'Edit details',exact:true})).toBeVisible();await page.goto(`/venues/${id}/assessment`);await expect(page.getByRole('button',{name:'Save and view requirements',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit assessment',exact:true})).toBeVisible();
 const db=new DatabaseSync(process.env['E2E_DATABASE_PATH']!);const emails=Object.fromEntries(['ems','director'].map(role=>{const email=`browser-${role}@venue.example.test`;db.prepare('UPDATE accounts SET email=? WHERE login=?').run(email,`test_${role}`);return[role,email]}));db.close();
 await page.goto(`/venues/${id}/team`);
 for(const kind of ['ems','director']){const f=page.locator('form').filter({has:page.locator(`input[name=kind][value=${kind}]`)});await f.locator('input[name=name]').fill(`Venue ${kind}`);await f.locator('input[name=email]').fill(emails[kind]!);await f.getByRole('button',{name:'Send invitation',exact:true}).click();await expect(page).toHaveURL(/invited=yes/);}
 // The URL already reads invited=yes after the first invitation, so wait for both rows to exist.
 await expect.poll(()=>{const f=new DatabaseSync(process.env['E2E_DATABASE_PATH']!);const n=(f.prepare('SELECT COUNT(*) AS n FROM venue_invitations WHERE venue_id=?').get(id) as {n:number}).n;f.close();return n;}).toBe(2);
 const fixture=new DatabaseSync(process.env['E2E_DATABASE_PATH']!);const invitations=fixture.prepare('SELECT kind,token FROM venue_invitations WHERE venue_id=?').all(id) as unknown as {kind:string;token:string}[];fixture.close();
 const staff=await browser.newPage({baseURL:baseURL!});await signInAs(staff,'test_ems');expect((await staff.request.get(`/venue-team/${id}`)).status()).toBe(404);
 await staff.goto(`/venue-invitations/${invitations.find(i=>i.kind==='ems')!.token}`);await staff.locator('input[name=phone]').fill('+9613111111');await staff.getByRole('button',{name:'Accept invitation',exact:true}).click();await expect(staff).toHaveURL(new RegExp(`/venue-team/${id}`));
 const keys=await staff.locator('[data-requirement]').filter({has:staff.locator('form')}).evaluateAll(rows=>rows.map(r=>r.getAttribute('data-requirement')!));expect(keys).toContain('5');expect(keys).not.toContain('15');
 const emsRow=await rowOpen(staff,'7');await expect(emsRow.locator('textarea[name=agency],textarea[name=phone]')).toHaveCount(0);await expect(emsRow.locator('textarea[name=arrangements]')).toBeVisible();
 const blsRow=await rowOpen(staff,'5');await expect(blsRow.locator('textarea')).toHaveCount(1);
 await expect(staff.locator('[data-region=linked-medical-team]')).toContainText('Venue ems');await expect(staff.locator('[data-region=linked-medical-team]')).toContainText('+9613111111');
 await page.goto(`/venues/${id}/requirements`);const pending=await rowOpen(page,'7');await expect(pending.locator('textarea,dd')).toHaveCount(0);await expect(pending).toContainText('Your medical team completes this item.');

 for(const key of keys)await fillRow(staff,key,true);
 await page.goto(`/venues/${id}/requirements`);await expect(page.locator('[data-requirement="5"] [data-completion]')).toHaveAttribute('data-completion','complete');await (await rowOpen(page,'5')).getByText(/Completed by/).waitFor();await expect(await rowOpen(page,'7')).toContainText('Confirmed 7 coverage');await expect(page.locator('[data-requirement="2"] summary')).toContainText('Awaiting approval');
 await page.goto(`/venues/${id}/requirements`);await fillRow(page,'10');await fillRow(page,'17');await page.goto(`/venues/${id}/submit`);await expect(page.getByRole('button',{name:/^Submit to the Ministry — \d+ remaining$/})).toBeDisabled();
 const director=await browser.newPage({baseURL:baseURL!});await signInAs(director,'test_director');await director.goto(`/venue-invitations/${invitations.find(i=>i.kind==='director')!.token}`);await director.locator('input[name=phone]').fill('+9613111111');await director.locator('input[name=licence]').fill('LIC-TEST');await director.getByRole('button',{name:'Accept invitation',exact:true}).click();await expect(director).toHaveURL(new RegExp(`/venue-team/${id}`));await fillRow(director,'15',true);
 const plan=await rowOpen(director,'2');const approve=plan.locator('form').filter({has:director.getByRole('button',{name:'Approve medical plan',exact:true})});await approve.locator('input[name=confirm]').check();await approve.getByRole('button',{name:'Approve medical plan',exact:true}).click();await expect(director).toHaveURL(/approval=recorded/);
 await page.goto(`/venues/${id}/submit`);await expect(page.getByRole('button',{name:'Submit to the Ministry — 1 remaining',exact:true})).toBeDisabled();await page.locator('input[name=confirm]').check();await expect(page.getByRole('button',{name:'Submit to the Ministry',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Submit to the Ministry',exact:true}).click();await expect(page).toHaveURL(/submitted=yes/);
 await staff.reload();await expect(staff.locator('main textarea')).toHaveCount(0);await expect(staff.locator('main')).toContainText('Read-only');
 await signInAs(director,'test_moph');await director.goto(`/ministry/venues/${id}`);await expect(director.locator('main')).toContainText('Medical Director approval');await expect(director.locator('main')).toContainText('Confirmed 5 coverage');await expect(director.getByRole('link',{name:/Open document/})).toHaveCount(3);await director.getByRole('button',{name:'Requirements satisfied',exact:true}).click();
 await page.goto(`/venues/${id}`);await expect(page.getByRole('link',{name:'Download venue certificate',exact:true})).toBeVisible();await expect(page.locator('[data-region=rail]')).toContainText('Stage 5 of 5');await page.screenshot({path:info.outputPath('venue-completed.png'),fullPage:true});await page.goto(`/venues/${id}/details`);await expect(page.getByRole('button',{name:'Edit details',exact:true})).toHaveCount(0);
 await staff.close();await director.close();
});
