// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/credentials" | "/dashboard" | "/events/[id]" | "/events/[id]/acknowledgment" | "/events/[id]/change" | "/events/[id]/declaration" | "/events/[id]/documents" | "/events/[id]/edit" | "/events/[id]/governance" | "/events/[id]/incident" | "/events/[id]/lifecycle" | "/events/[id]/participation" | "/events/[id]/plan" | "/events/[id]/post-event" | "/events/[id]/reassess" | "/events/[id]/report" | "/events/[id]/requirements" | "/events/[id]/submit" | "/events/new" | "/facilities/[id]" | "/facilities/[id]/devices" | "/facilities/[id]/incidents/new" | "/facilities/[id]/plan" | "/facilities/new" | "/first-response/readiness" | "/first-response/reports/new" | "/invitations/[token]" | "/ministry" | "/ministry/admin/cardiac" | "/ministry/admin/configuration" | "/ministry/admin/registry" | "/ministry/admin/users" | "/ministry/applicability" | "/ministry/changes" | "/ministry/determinations" | "/ministry/enquiries" | "/ministry/facilities" | "/ministry/facilities/arrests" | "/ministry/incidents" | "/ministry/order" | "/ministry/organizations" | "/ministry/queue" | "/ministry/submissions/[id]" | "/notifications" | "/organization" | "/platform/activity" | "/platform/admin" | "/profile" | "/signin" | "/venues/[id]" | "/venues/[id]/assessment" | "/venues/[id]/change" | "/venues/new"
type AppRouteHandlerRoutes = "/api/public/reference-lookup"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/public/reference-lookup": {}
  "/credentials": {}
  "/dashboard": {}
  "/events/[id]": { "id": string; }
  "/events/[id]/acknowledgment": { "id": string; }
  "/events/[id]/change": { "id": string; }
  "/events/[id]/declaration": { "id": string; }
  "/events/[id]/documents": { "id": string; }
  "/events/[id]/edit": { "id": string; }
  "/events/[id]/governance": { "id": string; }
  "/events/[id]/incident": { "id": string; }
  "/events/[id]/lifecycle": { "id": string; }
  "/events/[id]/participation": { "id": string; }
  "/events/[id]/plan": { "id": string; }
  "/events/[id]/post-event": { "id": string; }
  "/events/[id]/reassess": { "id": string; }
  "/events/[id]/report": { "id": string; }
  "/events/[id]/requirements": { "id": string; }
  "/events/[id]/submit": { "id": string; }
  "/events/new": {}
  "/facilities/[id]": { "id": string; }
  "/facilities/[id]/devices": { "id": string; }
  "/facilities/[id]/incidents/new": { "id": string; }
  "/facilities/[id]/plan": { "id": string; }
  "/facilities/new": {}
  "/first-response/readiness": {}
  "/first-response/reports/new": {}
  "/invitations/[token]": { "token": string; }
  "/ministry": {}
  "/ministry/admin/cardiac": {}
  "/ministry/admin/configuration": {}
  "/ministry/admin/registry": {}
  "/ministry/admin/users": {}
  "/ministry/applicability": {}
  "/ministry/changes": {}
  "/ministry/determinations": {}
  "/ministry/enquiries": {}
  "/ministry/facilities": {}
  "/ministry/facilities/arrests": {}
  "/ministry/incidents": {}
  "/ministry/order": {}
  "/ministry/organizations": {}
  "/ministry/queue": {}
  "/ministry/submissions/[id]": { "id": string; }
  "/notifications": {}
  "/organization": {}
  "/platform/activity": {}
  "/platform/admin": {}
  "/profile": {}
  "/signin": {}
  "/venues/[id]": { "id": string; }
  "/venues/[id]/assessment": { "id": string; }
  "/venues/[id]/change": { "id": string; }
  "/venues/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
