// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials">> = Specific
  const handler = {} as typeof import("../../app/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/acknowledgment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/acknowledgment">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/acknowledgment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/change/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/change">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/change/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/declaration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/declaration">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/declaration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/documents">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/governance">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/incident/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/incident">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/incident/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/lifecycle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/lifecycle">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/lifecycle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/participation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/participation">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/participation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/plan">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/post-event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/post-event">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/post-event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/reassess/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/reassess">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/reassess/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/report">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/requirements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/requirements">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/requirements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/submit">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/new">> = Specific
  const handler = {} as typeof import("../../app/events/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/facilities/[id]/devices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facilities/[id]/devices">> = Specific
  const handler = {} as typeof import("../../app/facilities/[id]/devices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/facilities/[id]/incidents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facilities/[id]/incidents/new">> = Specific
  const handler = {} as typeof import("../../app/facilities/[id]/incidents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/facilities/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facilities/[id]">> = Specific
  const handler = {} as typeof import("../../app/facilities/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/facilities/[id]/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facilities/[id]/plan">> = Specific
  const handler = {} as typeof import("../../app/facilities/[id]/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/facilities/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facilities/new">> = Specific
  const handler = {} as typeof import("../../app/facilities/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/first-response/readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/first-response/readiness">> = Specific
  const handler = {} as typeof import("../../app/first-response/readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/first-response/reports/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/first-response/reports/new">> = Specific
  const handler = {} as typeof import("../../app/first-response/reports/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invitations/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invitations/[token]">> = Specific
  const handler = {} as typeof import("../../app/invitations/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/admin/cardiac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/admin/cardiac">> = Specific
  const handler = {} as typeof import("../../app/ministry/admin/cardiac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/admin/configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/admin/configuration">> = Specific
  const handler = {} as typeof import("../../app/ministry/admin/configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/admin/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/admin/registry">> = Specific
  const handler = {} as typeof import("../../app/ministry/admin/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/admin/users">> = Specific
  const handler = {} as typeof import("../../app/ministry/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/applicability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/applicability">> = Specific
  const handler = {} as typeof import("../../app/ministry/applicability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/changes">> = Specific
  const handler = {} as typeof import("../../app/ministry/changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/determinations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/determinations">> = Specific
  const handler = {} as typeof import("../../app/ministry/determinations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/enquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/enquiries">> = Specific
  const handler = {} as typeof import("../../app/ministry/enquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/facilities/arrests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/facilities/arrests">> = Specific
  const handler = {} as typeof import("../../app/ministry/facilities/arrests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/facilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/facilities">> = Specific
  const handler = {} as typeof import("../../app/ministry/facilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/incidents">> = Specific
  const handler = {} as typeof import("../../app/ministry/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/order">> = Specific
  const handler = {} as typeof import("../../app/ministry/order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/organizations">> = Specific
  const handler = {} as typeof import("../../app/ministry/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry">> = Specific
  const handler = {} as typeof import("../../app/ministry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/queue">> = Specific
  const handler = {} as typeof import("../../app/ministry/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ministry/submissions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ministry/submissions/[id]">> = Specific
  const handler = {} as typeof import("../../app/ministry/submissions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization">> = Specific
  const handler = {} as typeof import("../../app/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/activity">> = Specific
  const handler = {} as typeof import("../../app/platform/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/admin">> = Specific
  const handler = {} as typeof import("../../app/platform/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venues/[id]/assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venues/[id]/assessment">> = Specific
  const handler = {} as typeof import("../../app/venues/[id]/assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venues/[id]/change/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venues/[id]/change">> = Specific
  const handler = {} as typeof import("../../app/venues/[id]/change/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venues/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venues/[id]">> = Specific
  const handler = {} as typeof import("../../app/venues/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venues/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venues/new">> = Specific
  const handler = {} as typeof import("../../app/venues/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/reference-lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reference-lookup">> = Specific
  const handler = {} as typeof import("../../app/api/public/reference-lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
