#!/usr/bin/env python3
"""
Extract the regulatory reference data from the design prototypes.

The nine assessment domains and the ten minimum conditions exist ONLY in
`handoff 4/pages/Organizer Journey.dc.html`. No markdown document enumerates them.
This script is the single supported way to refresh them.

It emits `lib/reference/reference-snapshot.json`, which records:
  - the domains and their 0/1/2 options, English and Arabic
  - the minimum conditions, their keys, levels and both languages
  - the prototype's own `derived:` expression for each condition, as provenance
  - a SHA-256 of the source file

The drift test compares the build's `lib/rules/data/*.json` against this snapshot AND
checks the SHA. If the reference HTML changes, the SHA no longer matches and the test
fails telling you to re-run this script. That is how reference drift gets caught rather
than discovered.

Usage:  npm run rules:regenerate
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

from jsparse import extract

PLATFORM = Path(__file__).resolve().parent.parent
REFERENCE = PLATFORM.parent / "handoff 4" / "pages" / "Organizer Journey.dc.html"
OUT = PLATFORM / "lib" / "reference" / "reference-snapshot.json"


def main() -> int:
    if not REFERENCE.exists():
        print(f"Reference file not found: {REFERENCE}", file=sys.stderr)
        return 1

    raw = REFERENCE.read_bytes()
    src = raw.decode("utf-8")

    domain_defs = extract(src, "domainDefs")
    min_defs = extract(src, "minDefs")

    if len(domain_defs) != 9:
        print(f"Expected 9 domains, found {len(domain_defs)}", file=sys.stderr)
        return 1
    if len(min_defs) != 10:
        print(f"Expected 10 minimum conditions, found {len(min_defs)}", file=sys.stderr)
        return 1

    domains = []
    for i, d in enumerate(domain_defs, start=1):
        opts = d["opts"]
        if len(opts) != 3:
            print(f"Domain {i} has {len(opts)} options, expected 3", file=sys.stderr)
            return 1
        domains.append(
            {
                "number": i,
                "en": d["en"],
                "ar": d["ar"],
                "noteEn": d.get("noteEn", ""),
                "noteAr": d.get("noteAr", ""),
                "options": [
                    {"score": score, "en": o[0], "ar": o[1]}
                    for score, o in enumerate(opts)
                ],
            }
        )

    conditions = []
    for m in min_defs:
        derived = m.get("derived")
        conditions.append(
            {
                "key": m["k"],
                "level": m["level"],
                "en": m["en"],
                "ar": m["ar"],
                # Provenance only. `false` means the prototype used a manual checkbox;
                # a string is the JS expression it derived from. Neither is what the
                # build does -- see lib/rules/data/minimum-conditions.json.
                "prototypeDerivedFrom": False if derived is False else str(derived),
            }
        )

    snapshot = {
        "$comment": (
            "GENERATED by scripts/extract-reference.py -- do not edit by hand. "
            "Re-run `npm run rules:regenerate` when the reference prototype changes."
        ),
        "sourceFile": str(REFERENCE.relative_to(PLATFORM.parent)),
        "sourceSha256": hashlib.sha256(raw).hexdigest(),
        "domains": domains,
        "minimumConditions": conditions,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(snapshot, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    manual = [c["key"] for c in conditions if c["prototypeDerivedFrom"] is False]
    print(f"Wrote {OUT.relative_to(PLATFORM)}")
    print(f"  {len(domains)} domains, {len(conditions)} minimum conditions")
    print(f"  source sha256: {snapshot['sourceSha256'][:16]}...")
    print(f"  manual in the prototype (must be derived in the build): {', '.join(manual)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
